# Generated by Django 3.2 on 2021-05-03 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importcsv', '0002_employee_preferred_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
