# Generated by Django 3.2 on 2021-05-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importcsv', '0003_auto_20210503_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('supermercado', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
